version: "3.8"

networks:
  inklusport-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: inklusport-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth_ms
    volumes:
      - ./init-mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - inklusport-network

  auth-service:
    build:
      context: ./backend/ink-ms-auth
      dockerfile: Dockerfile
    container_name: ink-ms-auth
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - inklusport-network

volumes:
  mysql_data: