spring:
  application:
    name: ink-ms-ai-assistant

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ai_chatbot_db}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:3008}

jwt:
  secret: ${JWT_SECRET:inklusport2024superSecretKeyForJWTtokenGenerationWith512bitsAlgorithmHS512}
  expiration: ${JWT_EXPIRATION:86400000}

gemini:
  api:
    key: AQ.Ab8RN6K7U2waqLdXBDSLRDAhAkEsQLSYKu6UahlcYdVJipttjA #
    model: ${GEMINI_MODEL:gemini-2.0-flash}
    temperature: ${GEMINI_TEMPERATURE:0.7}
    max-tokens: ${GEMINI_MAX_TOKENS:500}

logging:
  level:
    com.inklusport.ai: ${LOG_LEVEL:DEBUG}
    org.springframework.security: INFO