spring:
  application:
    name: ink-ms-ai-assistant

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/ai_chatbot_db}
      auto-index-creation: true

server:
  port: 3008

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: ${GEMINI_MODEL:gemini-2.0-flash}
    temperature: ${GEMINI_TEMPERATURE:0.7}
    max-tokens: ${GEMINI_MAX_TOKENS:500}

logging:
  level:
    com.inklusport.ai: INFO