spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: ${USER_NAME}
    password: ${USER_PASSWORD}

users:
  service:
    url: ${USERS_SERVICE_URL}
