spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-sports}:${DB_PORT:3306}/${DB_NAME:sports_events_ms}?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}

users:
  service:
    url: ${USERS_SERVICE_URL:http://ink-ms-users:3002}
