spring:
  application:
    name: ink-ms-gateway
  
  cloud:
    gateway:
      routes:
        # 1. Auth Service
        - id: auth-ms
          uri: http://auth-service:3001
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # 2. Users Service
        - id: users-ms
          uri: http://users-service:3002
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        # 3. Sports Service
        - id: sports-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/sports/**
          filters:
            - StripPrefix=0

        - id: events-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=0

        - id: disabilities-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/disabilities/**
          filters:
            - StripPrefix=0

        - id: SportsDisabilities-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/sport-disabilities/**
          filters:
            - StripPrefix=0

        - id: registrations-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/registrations/**
          filters:
            - StripPrefix=0

        - id: calendar-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/calendar/**
          filters:
            - StripPrefix=0

        - id: attendance-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/attendance/**
          filters:
            - StripPrefix=0

        # 4. Accessibility Service
        - id: accessibility-ms
          uri: http://accessibility-service:3004
          predicates:
            - Path=/api/preferences/**
          filters:
            - StripPrefix=0

        - id: notifications-ms
          uri: http://accessibility-service:3004
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0

        # 5. Reports Service
        - id: reports-ms
          uri: http://reports-service:3007
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=0

        - id: dashboard-ms
          uri: http://reports-service:3007
          predicates:
            - Path=/api/dashboard/**
          filters:
            - StripPrefix=0

server:
  port: 8080

security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG