spring:
  application:
    name: ink-ms-gateway
  
  cloud:
    gateway:
      routes:
        # Auth
        - id: auth-ms
          uri: http://auth-service:3001
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Users
        - id: users-ms
          uri: http://users-service:3002
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # Sports
        - id: sports-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/sports/**
          filters:
            - StripPrefix=1

        # Events (Sports)
        - id: events-ms
          uri: http://sports-service:3003
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1

        # Accessibility
        - id: accessibility-ms
          uri: http://accessibility-service:3004
          predicates:
            - Path=/api/preferences/**
          filters:
            - StripPrefix=1

        # Notifications (Accessibility)
        - id: notifications-ms
          uri: http://accessibility-service:3004
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

server:
  port: 8080

security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG