spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-user}:${DB_PORT:3306}/${DB_NAME:user_ms}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://ink-ms-auth:3001}
