spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-admin}:${DB_PORT:3306}/${DB_NAME:admin_ms}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

users:
  service:
    url: ${USERS_SERVICE_URL:http://ink-ms-users:3002}
