spring:
  application:
    name: ink-ms-sports
  
  datasource:
    url: jdbc:mysql://mysql:3306/sports_events_ms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 3003

auth:
  service:
    url: http://auth-service:3001

security:
  basic:
    enabled: false

accessibility:
  service:
    url: http://accessibility-service:3004

logging:
  level:
    com.inklusport.sports: DEBUG